name = "Lust Voidcraft"
author = "aria, voidfemme"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42672d0cf0d851c216e3ad459b134ae4ec8b0e22a50c938c086420ba6232c4b4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
