name = "Lust Voidcraft"
author = "aria, voidfemme"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e378e6a61aa71686ccfc963240288b7f8d02d8d80e9ab1120a480465893054d0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
