
[charms]
	#Disable Charged Regeneration Charm
	disableRegenCharm = false
	#Disable Charged Absorption Charm
	disableAbsorptionCharm = false
	#Disable Charged Glow Up Charm
	disableGlowupCharm = false
	#Disable Charged Totem Charm
	disableTotemCharm = false
	#Disable Charged Enchanted Totem Charm
	disableEnchTotemCharm = false
	#Disable Charged Speed Charm
	disableSpeedCharm = false
	#Disable Charged Water Breathing Charm
	disableWaterBreathingCharm = false

[tweaks]
	#Cooldown in seconds for the Charged Absorption Charm.
	#Range: 0 ~ 300
	absorptionCooldown = 20
	#Duration in seconds for the Charged Absorption Charm effect.
	#Range: 1 ~ 300
	absorptionDuration = 5
	#Charged Absorption Charm effect amplifier.
	#Range: 0 ~ 255
	absorptionAmplifier = 0
	#Number of charges for the Charged Absorption Charm.
	#Range: 1 ~ 100
	absorptionCharges = 15
	#Low health percentage to trigger Charged Regeneration Charm.
	#Range: 0.2 ~ 0.8
	regenPercentage = 0.35
	#Duration in seconds for the Charged Regeneration Charm effect.
	#Range: 1 ~ 300
	regenDuration = 15
	#Charged Regeneration Charm effect amplifier.
	#Range: 0 ~ 255
	regenAmplifier = 0
	#Number of charges for the Charged Regeneration Charm.
	#Range: 1 ~ 100
	regenCharges = 15
	#Duration in seconds for the Charged Glow Up Charm effect.
	#Range: 1 ~ 300
	glowUpDuration = 30
	#Number of charges for the Charged Glow Up Charm.
	#Range: 1 ~ 100
	glowUpCharges = 20
	#Duration in seconds for the Charged Speed Charm effect.
	#Range: 1 ~ 360
	speedDuration = 180
	#Cooldown in seconds for the Charged Speed Charm.
	#Range: 0 ~ 360
	speedCooldown = 120
	#Number of charges for the Charged Speed Charm.
	#Range: 1 ~ 100
	speedCharges = 20
	#Number of charges for the Charged Totem Charm and Charged Enchanted Totem Charm.
	#Range: 1 ~ 100
	totemCharges = 5
	#Amount of air remaining when Charged Water Breathing Charm is triggered.
	#Range: 0 ~ 10
	airRemaining = 0
	#Number of charges for the Charged Water Breathing Charm.
	#Range: 1 ~ 100
	waterBreathingCharges = 5

