
[General]
	#Renders some special effects from relics as icons above the food bar. This does not include SwiftEdge and RunicPlate icons.
	specialEffectIcons = true

["Weaver's Spool"]
	#The corner which the silk bar is rendered at.
	#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	silkBarCorner = "BOTTOM_RIGHT"

[Cyberpsychosis]
	#Disguises some passive and neutral mobs as hostile mobs while the Cyberpsychosis effect is active.
	cyberpsychosisDisguiseEffect = true

["Wonder of U"]
	#The black and white + outline effect of nullification.
	nullificationVisualEffect = true

[Swiftedge]
	#Renders sword icons above the food bar to show current stacks.
	swiftedgeStackIcons = true

["Runic Plate"]
	#Renders shield icons above the food bar to show current stacks.
	runicPlateStackIcons = true

["Guts Orb"]
	#Renders a little icon to show ability status above the food bar when enabled.
	gutsOrbIcon = true

["Opal Necklace"]
	#Renders a little icon to show ability status above the food bar when enabled.
	opalNecklaceIcon = true

["Made in Heaven"]
	#Renders a little icon to show ability status above the food bar when enabled.
	heavenIcon = true

[Moodworm]
	#Renders a little icon to show ability status above the food bar when enabled.
	moodwormIcon = true

